[package]
name = "collisions"
version = "0.1.0"
authors = ["Steve Mostovoy <stevemostovoysm@gmail.com>"]
edition = "2021"

[lib]
name = "collisions"

[dependencies]
parry2d = "0.17.0"
nalgebra = "0.33.0"